import { m } from "@oliumbi/i18n/messages";

const labels: Record<string, () => string> = {
	name: m.studio_field_name,
	title: m.studio_field_title,
	description: m.studio_field_description,
	body: m.studio_field_body,
	image_id: m.studio_field_image_id,
	visible: m.studio_field_visible,
	reservable: m.studio_field_reservable,
	starts_at: m.studio_field_starts_at,
	ends_at: m.studio_field_ends_at,
	starts_on: m.studio_field_starts_on,
	ends_on: m.studio_field_ends_on,
	published: m.studio_field_published,
	published_on: m.studio_field_published_on,
	slug: m.studio_field_slug,
	link: m.studio_field_link,
	author: m.studio_field_author,
	location: m.studio_field_location,
	guest_count: m.studio_field_guest_count,
	stars: m.studio_field_stars,
	status: m.studio_field_status,
	email: m.studio_field_email,
	phone: m.studio_field_phone,
	note: m.studio_field_note,
	event_on: m.studio_field_event_on,
	message: m.studio_field_message,
	group_name: m.studio_field_group_name,
	contact: m.studio_field_contact,
	quantity: m.studio_field_quantity,
	step: m.studio_field_step,
	unit: m.studio_field_unit,
	price: m.studio_field_price,
	product_id: m.studio_field_product_id,
	product_variant_id: m.studio_field_product_variant_id,
	donation_id: m.studio_field_donation_id,
	donation_item_id: m.studio_field_donation_item_id,
	story_id: m.studio_field_story_id,
	article_id: m.studio_field_article_id,
	showcase_id: m.studio_field_showcase_id,
	subject: m.studio_field_subject,
	requested_at: m.studio_field_requested_at,
	confirmed_at: m.studio_field_confirmed_at,
	unsubscribed_at: m.studio_field_unsubscribed_at,
	product_name: m.studio_field_product_name,
	variant_name: m.studio_field_variant_name,
	variant_description: m.studio_field_variant_description,
	variant_quantity: m.studio_field_variant_quantity,
	variant_price: m.studio_field_variant_price,
	donation_title: m.studio_field_donation_title,
	item_name: m.studio_field_item_name,
	item_description: m.studio_field_item_description,
	item_quantity: m.studio_field_item_quantity,
	item_step: m.studio_field_item_step,
	item_unit: m.studio_field_item_unit,
};
export function fieldLabel(name: string, fallback: string) {
	return labels[name]?.() ?? fallback;
}
