import type { ResourceDefinition } from "@oliumbi/contracts";
export const zelglihofProductReservation = {
	table: "zelglihof.product_reservation",
	label: "Reservationen",
	fields: [
		{
			name: "product_id",
			label: "product id",
			kind: "uuid",
			nullable: true,
			readOnly: true,
		},
		{
			name: "product_variant_id",
			label: "product variant id",
			kind: "uuid",
			nullable: true,
			readOnly: true,
		},
		{
			name: "product_name",
			label: "product name",
			kind: "text",
			readOnly: true,
		},
		{
			name: "variant_name",
			label: "variant name",
			kind: "text",
			readOnly: true,
		},
		{
			name: "variant_description",
			label: "variant description",
			kind: "text",
			nullable: true,
			readOnly: true,
		},
		{
			name: "variant_quantity",
			label: "variant quantity",
			kind: "number",
			nullable: true,
			integer: true,
			readOnly: true,
		},
		{
			name: "variant_price",
			label: "variant price",
			kind: "text",
			readOnly: true,
		},
		{
			name: "name",
			label: "name",
			kind: "text",
			readOnly: true,
		},
		{
			name: "phone",
			label: "phone",
			kind: "text",
			readOnly: true,
		},
		{
			name: "email",
			label: "email",
			kind: "email",
			nullable: true,
			readOnly: true,
		},
		{
			name: "quantity",
			label: "quantity",
			kind: "number",
			integer: true,
			readOnly: true,
		},
		{
			name: "note",
			label: "note",
			kind: "textarea",
			nullable: true,
			readOnly: true,
		},
		{
			name: "status",
			label: "status",
			kind: "status",
		},
	],
	create: false,
	edit: true,
	delete: true,
} as const satisfies ResourceDefinition;
