server:
  port: 8081
spring:
  datasource:
    url: jdbc:${DATABASE_URL}
    username: ${IDENTITY_DATABASE_USER}
    password: ${IDENTITY_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
management:
  endpoints:
    web:
      exposure:
        include: health
springdoc:
  swagger-ui:
    path: /docs
identity:
  authorization-token: ${IDENTITY_INTERNAL_AUTHORIZATION_TOKEN}
  session-expiration-days: 7
