/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgbRouteImport } from './routes/agb'
import { Route as AnfragenRouteImport } from './routes/anfragen'
import { Route as AngebotRouteImport } from './routes/angebot'
import { Route as CateringRouteImport } from './routes/catering'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as EinblickeRouteImport } from './routes/einblicke'
import { Route as GeschaeftsbedingungRouteImport } from './routes/geschaeftsbedingung'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as KurseRouteImport } from './routes/kurse'
import { Route as PrivatkochRouteImport } from './routes/privatkoch'
import { Route as UeberMichRouteImport } from './routes/ueber-mich'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgbRoute = AgbRouteImport.update({
  id: '/agb',
  path: '/agb',
  getParentRoute: () => rootRouteImport,
} as any)
const AnfragenRoute = AnfragenRouteImport.update({
  id: '/anfragen',
  path: '/anfragen',
  getParentRoute: () => rootRouteImport,
} as any)
const AngebotRoute = AngebotRouteImport.update({
  id: '/angebot',
  path: '/angebot',
  getParentRoute: () => rootRouteImport,
} as any)
const CateringRoute = CateringRouteImport.update({
  id: '/catering',
  path: '/catering',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const EinblickeRoute = EinblickeRouteImport.update({
  id: '/einblicke',
  path: '/einblicke',
  getParentRoute: () => rootRouteImport,
} as any)
const GeschaeftsbedingungRoute = GeschaeftsbedingungRouteImport.update({
  id: '/geschaeftsbedingung',
  path: '/geschaeftsbedingung',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const KurseRoute = KurseRouteImport.update({
  id: '/kurse',
  path: '/kurse',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivatkochRoute = PrivatkochRouteImport.update({
  id: '/privatkoch',
  path: '/privatkoch',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberMichRoute = UeberMichRouteImport.update({
  id: '/ueber-mich',
  path: '/ueber-mich',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/anfragen': typeof AnfragenRoute
  '/angebot': typeof AngebotRoute
  '/catering': typeof CateringRoute
  '/datenschutz': typeof DatenschutzRoute
  '/einblicke': typeof EinblickeRoute
  '/geschaeftsbedingung': typeof GeschaeftsbedingungRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/kurse': typeof KurseRoute
  '/privatkoch': typeof PrivatkochRoute
  '/ueber-mich': typeof UeberMichRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/anfragen': typeof AnfragenRoute
  '/angebot': typeof AngebotRoute
  '/catering': typeof CateringRoute
  '/datenschutz': typeof DatenschutzRoute
  '/einblicke': typeof EinblickeRoute
  '/geschaeftsbedingung': typeof GeschaeftsbedingungRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/kurse': typeof KurseRoute
  '/privatkoch': typeof PrivatkochRoute
  '/ueber-mich': typeof UeberMichRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/anfragen': typeof AnfragenRoute
  '/angebot': typeof AngebotRoute
  '/catering': typeof CateringRoute
  '/datenschutz': typeof DatenschutzRoute
  '/einblicke': typeof EinblickeRoute
  '/geschaeftsbedingung': typeof GeschaeftsbedingungRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/kurse': typeof KurseRoute
  '/privatkoch': typeof PrivatkochRoute
  '/ueber-mich': typeof UeberMichRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agb'
    | '/anfragen'
    | '/angebot'
    | '/catering'
    | '/datenschutz'
    | '/einblicke'
    | '/geschaeftsbedingung'
    | '/impressum'
    | '/kontakt'
    | '/kurse'
    | '/privatkoch'
    | '/ueber-mich'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agb'
    | '/anfragen'
    | '/angebot'
    | '/catering'
    | '/datenschutz'
    | '/einblicke'
    | '/geschaeftsbedingung'
    | '/impressum'
    | '/kontakt'
    | '/kurse'
    | '/privatkoch'
    | '/ueber-mich'
  id:
    | '__root__'
    | '/'
    | '/agb'
    | '/anfragen'
    | '/angebot'
    | '/catering'
    | '/datenschutz'
    | '/einblicke'
    | '/geschaeftsbedingung'
    | '/impressum'
    | '/kontakt'
    | '/kurse'
    | '/privatkoch'
    | '/ueber-mich'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgbRoute: typeof AgbRoute
  AnfragenRoute: typeof AnfragenRoute
  AngebotRoute: typeof AngebotRoute
  CateringRoute: typeof CateringRoute
  DatenschutzRoute: typeof DatenschutzRoute
  EinblickeRoute: typeof EinblickeRoute
  GeschaeftsbedingungRoute: typeof GeschaeftsbedingungRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  KurseRoute: typeof KurseRoute
  PrivatkochRoute: typeof PrivatkochRoute
  UeberMichRoute: typeof UeberMichRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agb': {
      id: '/agb'
      path: '/agb'
      fullPath: '/agb'
      preLoaderRoute: typeof AgbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anfragen': {
      id: '/anfragen'
      path: '/anfragen'
      fullPath: '/anfragen'
      preLoaderRoute: typeof AnfragenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/angebot': {
      id: '/angebot'
      path: '/angebot'
      fullPath: '/angebot'
      preLoaderRoute: typeof AngebotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catering': {
      id: '/catering'
      path: '/catering'
      fullPath: '/catering'
      preLoaderRoute: typeof CateringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/einblicke': {
      id: '/einblicke'
      path: '/einblicke'
      fullPath: '/einblicke'
      preLoaderRoute: typeof EinblickeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geschaeftsbedingung': {
      id: '/geschaeftsbedingung'
      path: '/geschaeftsbedingung'
      fullPath: '/geschaeftsbedingung'
      preLoaderRoute: typeof GeschaeftsbedingungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kurse': {
      id: '/kurse'
      path: '/kurse'
      fullPath: '/kurse'
      preLoaderRoute: typeof KurseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privatkoch': {
      id: '/privatkoch'
      path: '/privatkoch'
      fullPath: '/privatkoch'
      preLoaderRoute: typeof PrivatkochRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueber-mich': {
      id: '/ueber-mich'
      path: '/ueber-mich'
      fullPath: '/ueber-mich'
      preLoaderRoute: typeof UeberMichRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgbRoute: AgbRoute,
  AnfragenRoute: AnfragenRoute,
  AngebotRoute: AngebotRoute,
  CateringRoute: CateringRoute,
  DatenschutzRoute: DatenschutzRoute,
  EinblickeRoute: EinblickeRoute,
  GeschaeftsbedingungRoute: GeschaeftsbedingungRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  KurseRoute: KurseRoute,
  PrivatkochRoute: PrivatkochRoute,
  UeberMichRoute: UeberMichRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
