/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as InquiryRouteImport } from './routes/inquiry'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ShowcasesRouteImport } from './routes/showcases'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ShowcasesSlugRouteImport } from './routes/showcases/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiryRoute = InquiryRouteImport.update({
  id: '/inquiry',
  path: '/inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcasesRoute = ShowcasesRouteImport.update({
  id: '/showcases',
  path: '/showcases',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcasesSlugRoute = ShowcasesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShowcasesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/inquiry': typeof InquiryRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/showcases': typeof ShowcasesRouteWithChildren
  '/terms': typeof TermsRoute
  '/showcases/$slug': typeof ShowcasesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/inquiry': typeof InquiryRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/showcases': typeof ShowcasesRouteWithChildren
  '/terms': typeof TermsRoute
  '/showcases/$slug': typeof ShowcasesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/inquiry': typeof InquiryRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/showcases': typeof ShowcasesRouteWithChildren
  '/terms': typeof TermsRoute
  '/showcases/$slug': typeof ShowcasesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/inquiry'
    | '/legal'
    | '/privacy'
    | '/services'
    | '/showcases'
    | '/terms'
    | '/showcases/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/inquiry'
    | '/legal'
    | '/privacy'
    | '/services'
    | '/showcases'
    | '/terms'
    | '/showcases/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/inquiry'
    | '/legal'
    | '/privacy'
    | '/services'
    | '/showcases'
    | '/terms'
    | '/showcases/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  InquiryRoute: typeof InquiryRoute
  LegalRoute: typeof LegalRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  ShowcasesRoute: typeof ShowcasesRouteWithChildren
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiry': {
      id: '/inquiry'
      path: '/inquiry'
      fullPath: '/inquiry'
      preLoaderRoute: typeof InquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcases': {
      id: '/showcases'
      path: '/showcases'
      fullPath: '/showcases'
      preLoaderRoute: typeof ShowcasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcases/$slug': {
      id: '/showcases/$slug'
      path: '/$slug'
      fullPath: '/showcases/$slug'
      preLoaderRoute: typeof ShowcasesSlugRouteImport
      parentRoute: typeof ShowcasesRoute
    }
  }
}

interface ShowcasesRouteChildren {
  ShowcasesSlugRoute: typeof ShowcasesSlugRoute
}

const ShowcasesRouteChildren: ShowcasesRouteChildren = {
  ShowcasesSlugRoute: ShowcasesSlugRoute,
}

const ShowcasesRouteWithChildren = ShowcasesRoute._addFileChildren(
  ShowcasesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  InquiryRoute: InquiryRoute,
  LegalRoute: LegalRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  ShowcasesRoute: ShowcasesRouteWithChildren,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
