/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LatestRouteImport } from './routes/latest'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as NewsletterAbmeldenTokenRouteImport } from './routes/newsletter/abmelden/$token'
import { Route as NewsletterBestaetigenTokenRouteImport } from './routes/newsletter/bestaetigen/$token'
import { Route as ApiNewsletterAbmeldenTokenRouteImport } from './routes/api/newsletter/abmelden/$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LatestRoute = LatestRouteImport.update({
  id: '/latest',
  path: '/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterAbmeldenTokenRoute = NewsletterAbmeldenTokenRouteImport.update({
  id: '/newsletter/abmelden/$token',
  path: '/newsletter/abmelden/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterBestaetigenTokenRoute =
  NewsletterBestaetigenTokenRouteImport.update({
    id: '/newsletter/bestaetigen/$token',
    path: '/newsletter/bestaetigen/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiNewsletterAbmeldenTokenRoute =
  ApiNewsletterAbmeldenTokenRouteImport.update({
    id: '/api/newsletter/abmelden/$token',
    path: '/api/newsletter/abmelden/$token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/latest': typeof LatestRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/': typeof ProductsIndexRoute
  '/newsletter/abmelden/$token': typeof NewsletterAbmeldenTokenRoute
  '/newsletter/bestaetigen/$token': typeof NewsletterBestaetigenTokenRoute
  '/api/newsletter/abmelden/$token': typeof ApiNewsletterAbmeldenTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/latest': typeof LatestRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products': typeof ProductsIndexRoute
  '/newsletter/abmelden/$token': typeof NewsletterAbmeldenTokenRoute
  '/newsletter/bestaetigen/$token': typeof NewsletterBestaetigenTokenRoute
  '/api/newsletter/abmelden/$token': typeof ApiNewsletterAbmeldenTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/latest': typeof LatestRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/': typeof ProductsIndexRoute
  '/newsletter/abmelden/$token': typeof NewsletterAbmeldenTokenRoute
  '/newsletter/bestaetigen/$token': typeof NewsletterBestaetigenTokenRoute
  '/api/newsletter/abmelden/$token': typeof ApiNewsletterAbmeldenTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/latest'
    | '/legal'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/products/$productId'
    | '/products/'
    | '/newsletter/abmelden/$token'
    | '/newsletter/bestaetigen/$token'
    | '/api/newsletter/abmelden/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/latest'
    | '/legal'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/products/$productId'
    | '/products'
    | '/newsletter/abmelden/$token'
    | '/newsletter/bestaetigen/$token'
    | '/api/newsletter/abmelden/$token'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/latest'
    | '/legal'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/products/$productId'
    | '/products/'
    | '/newsletter/abmelden/$token'
    | '/newsletter/bestaetigen/$token'
    | '/api/newsletter/abmelden/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  LatestRoute: typeof LatestRoute
  LegalRoute: typeof LegalRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  NewsletterAbmeldenTokenRoute: typeof NewsletterAbmeldenTokenRoute
  NewsletterBestaetigenTokenRoute: typeof NewsletterBestaetigenTokenRoute
  ApiNewsletterAbmeldenTokenRoute: typeof ApiNewsletterAbmeldenTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latest': {
      id: '/latest'
      path: '/latest'
      fullPath: '/latest'
      preLoaderRoute: typeof LatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/abmelden/$token': {
      id: '/newsletter/abmelden/$token'
      path: '/newsletter/abmelden/$token'
      fullPath: '/newsletter/abmelden/$token'
      preLoaderRoute: typeof NewsletterAbmeldenTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/bestaetigen/$token': {
      id: '/newsletter/bestaetigen/$token'
      path: '/newsletter/bestaetigen/$token'
      fullPath: '/newsletter/bestaetigen/$token'
      preLoaderRoute: typeof NewsletterBestaetigenTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/newsletter/abmelden/$token': {
      id: '/api/newsletter/abmelden/$token'
      path: '/api/newsletter/abmelden/$token'
      fullPath: '/api/newsletter/abmelden/$token'
      preLoaderRoute: typeof ApiNewsletterAbmeldenTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  LatestRoute: LatestRoute,
  LegalRoute: LegalRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  NewsletterAbmeldenTokenRoute: NewsletterAbmeldenTokenRoute,
  NewsletterBestaetigenTokenRoute: NewsletterBestaetigenTokenRoute,
  ApiNewsletterAbmeldenTokenRoute: ApiNewsletterAbmeldenTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from '../../../../../../../web/sites/zelglihof/src/router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
