/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as LatestIndexRouteImport } from './routes/latest/index'
import { Route as LatestSlugRouteImport } from './routes/latest/$slug'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as NewsletterConfirmTokenRouteImport } from './routes/newsletter/confirm/$token'
import { Route as NewsletterUnsubscribeTokenRouteImport } from './routes/newsletter/unsubscribe/$token'
import { Route as ApiNewsletterUnsubscribeTokenRouteImport } from './routes/api/newsletter/unsubscribe/$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LatestIndexRoute = LatestIndexRouteImport.update({
  id: '/latest/',
  path: '/latest/',
  getParentRoute: () => rootRouteImport,
} as any)
const LatestSlugRoute = LatestSlugRouteImport.update({
  id: '/latest/$slug',
  path: '/latest/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterConfirmTokenRoute = NewsletterConfirmTokenRouteImport.update({
  id: '/newsletter/confirm/$token',
  path: '/newsletter/confirm/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterUnsubscribeTokenRoute =
  NewsletterUnsubscribeTokenRouteImport.update({
    id: '/newsletter/unsubscribe/$token',
    path: '/newsletter/unsubscribe/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiNewsletterUnsubscribeTokenRoute =
  ApiNewsletterUnsubscribeTokenRouteImport.update({
    id: '/api/newsletter/unsubscribe/$token',
    path: '/api/newsletter/unsubscribe/$token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/latest/$slug': typeof LatestSlugRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/latest/': typeof LatestIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/newsletter/confirm/$token': typeof NewsletterConfirmTokenRoute
  '/newsletter/unsubscribe/$token': typeof NewsletterUnsubscribeTokenRoute
  '/api/newsletter/unsubscribe/$token': typeof ApiNewsletterUnsubscribeTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/latest/$slug': typeof LatestSlugRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/latest': typeof LatestIndexRoute
  '/products': typeof ProductsIndexRoute
  '/newsletter/confirm/$token': typeof NewsletterConfirmTokenRoute
  '/newsletter/unsubscribe/$token': typeof NewsletterUnsubscribeTokenRoute
  '/api/newsletter/unsubscribe/$token': typeof ApiNewsletterUnsubscribeTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/latest/$slug': typeof LatestSlugRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/latest/': typeof LatestIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/newsletter/confirm/$token': typeof NewsletterConfirmTokenRoute
  '/newsletter/unsubscribe/$token': typeof NewsletterUnsubscribeTokenRoute
  '/api/newsletter/unsubscribe/$token': typeof ApiNewsletterUnsubscribeTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/legal'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/latest/$slug'
    | '/products/$productId'
    | '/latest/'
    | '/products/'
    | '/newsletter/confirm/$token'
    | '/newsletter/unsubscribe/$token'
    | '/api/newsletter/unsubscribe/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/legal'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/latest/$slug'
    | '/products/$productId'
    | '/latest'
    | '/products'
    | '/newsletter/confirm/$token'
    | '/newsletter/unsubscribe/$token'
    | '/api/newsletter/unsubscribe/$token'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/legal'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/latest/$slug'
    | '/products/$productId'
    | '/latest/'
    | '/products/'
    | '/newsletter/confirm/$token'
    | '/newsletter/unsubscribe/$token'
    | '/api/newsletter/unsubscribe/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  LegalRoute: typeof LegalRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  LatestSlugRoute: typeof LatestSlugRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  LatestIndexRoute: typeof LatestIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  NewsletterConfirmTokenRoute: typeof NewsletterConfirmTokenRoute
  NewsletterUnsubscribeTokenRoute: typeof NewsletterUnsubscribeTokenRoute
  ApiNewsletterUnsubscribeTokenRoute: typeof ApiNewsletterUnsubscribeTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latest/': {
      id: '/latest/'
      path: '/latest'
      fullPath: '/latest/'
      preLoaderRoute: typeof LatestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latest/$slug': {
      id: '/latest/$slug'
      path: '/latest/$slug'
      fullPath: '/latest/$slug'
      preLoaderRoute: typeof LatestSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/confirm/$token': {
      id: '/newsletter/confirm/$token'
      path: '/newsletter/confirm/$token'
      fullPath: '/newsletter/confirm/$token'
      preLoaderRoute: typeof NewsletterConfirmTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/unsubscribe/$token': {
      id: '/newsletter/unsubscribe/$token'
      path: '/newsletter/unsubscribe/$token'
      fullPath: '/newsletter/unsubscribe/$token'
      preLoaderRoute: typeof NewsletterUnsubscribeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/newsletter/unsubscribe/$token': {
      id: '/api/newsletter/unsubscribe/$token'
      path: '/api/newsletter/unsubscribe/$token'
      fullPath: '/api/newsletter/unsubscribe/$token'
      preLoaderRoute: typeof ApiNewsletterUnsubscribeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  LegalRoute: LegalRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  LatestSlugRoute: LatestSlugRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  LatestIndexRoute: LatestIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  NewsletterConfirmTokenRoute: NewsletterConfirmTokenRoute,
  NewsletterUnsubscribeTokenRoute: NewsletterUnsubscribeTokenRoute,
  ApiNewsletterUnsubscribeTokenRoute: ApiNewsletterUnsubscribeTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
