/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as EventsRouteImport } from './routes/events'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DonationsIndexRouteImport } from './routes/donations/index'
import { Route as DonationsDonationIdRouteImport } from './routes/donations/$donationId'
import { Route as EventsEventIdRouteImport } from './routes/events/$eventId'
import { Route as StoriesIndexRouteImport } from './routes/stories/index'
import { Route as StoriesSlugRouteImport } from './routes/stories/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationsIndexRoute = DonationsIndexRouteImport.update({
  id: '/donations/',
  path: '/donations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationsDonationIdRoute = DonationsDonationIdRouteImport.update({
  id: '/donations/$donationId',
  path: '/donations/$donationId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => EventsRoute,
} as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/stories/',
  path: '/stories/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesSlugRoute = StoriesSlugRouteImport.update({
  id: '/stories/$slug',
  path: '/stories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/events': typeof EventsRouteWithChildren
  '/join': typeof JoinRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/donations/$donationId': typeof DonationsDonationIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/donations/': typeof DonationsIndexRoute
  '/stories/': typeof StoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/events': typeof EventsRouteWithChildren
  '/join': typeof JoinRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/donations/$donationId': typeof DonationsDonationIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/donations': typeof DonationsIndexRoute
  '/stories': typeof StoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/events': typeof EventsRouteWithChildren
  '/join': typeof JoinRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/donations/$donationId': typeof DonationsDonationIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/donations/': typeof DonationsIndexRoute
  '/stories/': typeof StoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/events'
    | '/join'
    | '/legal'
    | '/privacy'
    | '/donations/$donationId'
    | '/events/$eventId'
    | '/stories/$slug'
    | '/donations/'
    | '/stories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/events'
    | '/join'
    | '/legal'
    | '/privacy'
    | '/donations/$donationId'
    | '/events/$eventId'
    | '/stories/$slug'
    | '/donations'
    | '/stories'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/events'
    | '/join'
    | '/legal'
    | '/privacy'
    | '/donations/$donationId'
    | '/events/$eventId'
    | '/stories/$slug'
    | '/donations/'
    | '/stories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EventsRoute: typeof EventsRouteWithChildren
  JoinRoute: typeof JoinRoute
  LegalRoute: typeof LegalRoute
  PrivacyRoute: typeof PrivacyRoute
  DonationsDonationIdRoute: typeof DonationsDonationIdRoute
  StoriesSlugRoute: typeof StoriesSlugRoute
  DonationsIndexRoute: typeof DonationsIndexRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donations/': {
      id: '/donations/'
      path: '/donations'
      fullPath: '/donations/'
      preLoaderRoute: typeof DonationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donations/$donationId': {
      id: '/donations/$donationId'
      path: '/donations/$donationId'
      fullPath: '/donations/$donationId'
      preLoaderRoute: typeof DonationsDonationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/stories/': {
      id: '/stories/'
      path: '/stories'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$slug': {
      id: '/stories/$slug'
      path: '/stories/$slug'
      fullPath: '/stories/$slug'
      preLoaderRoute: typeof StoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EventsRouteChildren {
  EventsEventIdRoute: typeof EventsEventIdRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsEventIdRoute: EventsEventIdRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EventsRoute: EventsRouteWithChildren,
  JoinRoute: JoinRoute,
  LegalRoute: LegalRoute,
  PrivacyRoute: PrivacyRoute,
  DonationsDonationIdRoute: DonationsDonationIdRoute,
  StoriesSlugRoute: StoriesSlugRoute,
  DonationsIndexRoute: DonationsIndexRoute,
  StoriesIndexRoute: StoriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
