/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnlaesseRouteImport } from './routes/anlaesse'
import { Route as BeitretenRouteImport } from './routes/beitreten'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as GeschichtenRouteImport } from './routes/geschichten'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as MitmachenRouteImport } from './routes/mitmachen'
import { Route as NewsRouteImport } from './routes/news'
import { Route as UeberUnsRouteImport } from './routes/ueber-uns'
import { Route as VeranstaltungenRouteImport } from './routes/veranstaltungen'
import { Route as AnlaesseSlugRouteImport } from './routes/anlaesse/$slug'
import { Route as GeschichtenSlugRouteImport } from './routes/geschichten/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnlaesseRoute = AnlaesseRouteImport.update({
  id: '/anlaesse',
  path: '/anlaesse',
  getParentRoute: () => rootRouteImport,
} as any)
const BeitretenRoute = BeitretenRouteImport.update({
  id: '/beitreten',
  path: '/beitreten',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const GeschichtenRoute = GeschichtenRouteImport.update({
  id: '/geschichten',
  path: '/geschichten',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const MitmachenRoute = MitmachenRouteImport.update({
  id: '/mitmachen',
  path: '/mitmachen',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberUnsRoute = UeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => rootRouteImport,
} as any)
const VeranstaltungenRoute = VeranstaltungenRouteImport.update({
  id: '/veranstaltungen',
  path: '/veranstaltungen',
  getParentRoute: () => rootRouteImport,
} as any)
const AnlaesseSlugRoute = AnlaesseSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AnlaesseRoute,
} as any)
const GeschichtenSlugRoute = GeschichtenSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GeschichtenRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anlaesse': typeof AnlaesseRouteWithChildren
  '/beitreten': typeof BeitretenRoute
  '/datenschutz': typeof DatenschutzRoute
  '/geschichten': typeof GeschichtenRouteWithChildren
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/mitmachen': typeof MitmachenRoute
  '/news': typeof NewsRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/veranstaltungen': typeof VeranstaltungenRoute
  '/anlaesse/$slug': typeof AnlaesseSlugRoute
  '/geschichten/$slug': typeof GeschichtenSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anlaesse': typeof AnlaesseRouteWithChildren
  '/beitreten': typeof BeitretenRoute
  '/datenschutz': typeof DatenschutzRoute
  '/geschichten': typeof GeschichtenRouteWithChildren
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/mitmachen': typeof MitmachenRoute
  '/news': typeof NewsRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/veranstaltungen': typeof VeranstaltungenRoute
  '/anlaesse/$slug': typeof AnlaesseSlugRoute
  '/geschichten/$slug': typeof GeschichtenSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anlaesse': typeof AnlaesseRouteWithChildren
  '/beitreten': typeof BeitretenRoute
  '/datenschutz': typeof DatenschutzRoute
  '/geschichten': typeof GeschichtenRouteWithChildren
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/mitmachen': typeof MitmachenRoute
  '/news': typeof NewsRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/veranstaltungen': typeof VeranstaltungenRoute
  '/anlaesse/$slug': typeof AnlaesseSlugRoute
  '/geschichten/$slug': typeof GeschichtenSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anlaesse'
    | '/beitreten'
    | '/datenschutz'
    | '/geschichten'
    | '/impressum'
    | '/kontakt'
    | '/mitmachen'
    | '/news'
    | '/ueber-uns'
    | '/veranstaltungen'
    | '/anlaesse/$slug'
    | '/geschichten/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anlaesse'
    | '/beitreten'
    | '/datenschutz'
    | '/geschichten'
    | '/impressum'
    | '/kontakt'
    | '/mitmachen'
    | '/news'
    | '/ueber-uns'
    | '/veranstaltungen'
    | '/anlaesse/$slug'
    | '/geschichten/$slug'
  id:
    | '__root__'
    | '/'
    | '/anlaesse'
    | '/beitreten'
    | '/datenschutz'
    | '/geschichten'
    | '/impressum'
    | '/kontakt'
    | '/mitmachen'
    | '/news'
    | '/ueber-uns'
    | '/veranstaltungen'
    | '/anlaesse/$slug'
    | '/geschichten/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnlaesseRoute: typeof AnlaesseRouteWithChildren
  BeitretenRoute: typeof BeitretenRoute
  DatenschutzRoute: typeof DatenschutzRoute
  GeschichtenRoute: typeof GeschichtenRouteWithChildren
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  MitmachenRoute: typeof MitmachenRoute
  NewsRoute: typeof NewsRoute
  UeberUnsRoute: typeof UeberUnsRoute
  VeranstaltungenRoute: typeof VeranstaltungenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anlaesse': {
      id: '/anlaesse'
      path: '/anlaesse'
      fullPath: '/anlaesse'
      preLoaderRoute: typeof AnlaesseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beitreten': {
      id: '/beitreten'
      path: '/beitreten'
      fullPath: '/beitreten'
      preLoaderRoute: typeof BeitretenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geschichten': {
      id: '/geschichten'
      path: '/geschichten'
      fullPath: '/geschichten'
      preLoaderRoute: typeof GeschichtenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitmachen': {
      id: '/mitmachen'
      path: '/mitmachen'
      fullPath: '/mitmachen'
      preLoaderRoute: typeof MitmachenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueber-uns': {
      id: '/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/ueber-uns'
      preLoaderRoute: typeof UeberUnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veranstaltungen': {
      id: '/veranstaltungen'
      path: '/veranstaltungen'
      fullPath: '/veranstaltungen'
      preLoaderRoute: typeof VeranstaltungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anlaesse/$slug': {
      id: '/anlaesse/$slug'
      path: '/$slug'
      fullPath: '/anlaesse/$slug'
      preLoaderRoute: typeof AnlaesseSlugRouteImport
      parentRoute: typeof AnlaesseRoute
    }
    '/geschichten/$slug': {
      id: '/geschichten/$slug'
      path: '/$slug'
      fullPath: '/geschichten/$slug'
      preLoaderRoute: typeof GeschichtenSlugRouteImport
      parentRoute: typeof GeschichtenRoute
    }
  }
}

interface AnlaesseRouteChildren {
  AnlaesseSlugRoute: typeof AnlaesseSlugRoute
}

const AnlaesseRouteChildren: AnlaesseRouteChildren = {
  AnlaesseSlugRoute: AnlaesseSlugRoute,
}

const AnlaesseRouteWithChildren = AnlaesseRoute._addFileChildren(
  AnlaesseRouteChildren,
)

interface GeschichtenRouteChildren {
  GeschichtenSlugRoute: typeof GeschichtenSlugRoute
}

const GeschichtenRouteChildren: GeschichtenRouteChildren = {
  GeschichtenSlugRoute: GeschichtenSlugRoute,
}

const GeschichtenRouteWithChildren = GeschichtenRoute._addFileChildren(
  GeschichtenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnlaesseRoute: AnlaesseRouteWithChildren,
  BeitretenRoute: BeitretenRoute,
  DatenschutzRoute: DatenschutzRoute,
  GeschichtenRoute: GeschichtenRouteWithChildren,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  MitmachenRoute: MitmachenRoute,
  NewsRoute: NewsRoute,
  UeberUnsRoute: UeberUnsRoute,
  VeranstaltungenRoute: VeranstaltungenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
