server:
  port: 8081
spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${IDENTITY_DATABASE_USER}
    password: ${IDENTITY_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
management:
  endpoints:
    web:
      exposure:
        include: health
identity:
  authorization-token: ${IDENTITY_INTERNAL_AUTHORIZATION_TOKEN}
  session-expiration-days: 7
