CREATE SCHEMA studio;
CREATE SCHEMA jublawoma;
CREATE SCHEMA unclet;
CREATE SCHEMA zelglihof;
CREATE SCHEMA oliumbi;
CREATE SCHEMA identity;
CREATE SCHEMA messaging;
CREATE SCHEMA media;

REVOKE CREATE ON SCHEMA public FROM PUBLIC;

CREATE ROLE studio LOGIN PASSWORD 'root';
CREATE ROLE jublawoma LOGIN PASSWORD 'root';
CREATE ROLE unclet LOGIN PASSWORD 'root';
CREATE ROLE zelglihof LOGIN PASSWORD 'root';
CREATE ROLE oliumbi LOGIN PASSWORD 'root';
CREATE ROLE identity LOGIN PASSWORD 'root';
CREATE ROLE messaging LOGIN PASSWORD 'root';
CREATE ROLE media LOGIN PASSWORD 'root';

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA studio TO studio;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA jublawoma TO jublawoma, studio;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA unclet TO unclet, studio;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA zelglihof TO zelglihof, studio;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA oliumbi TO oliumbi, studio;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA identity TO identity;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA messaging TO messaging;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA media TO media;
