/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZelglihofRouteRouteImport } from './routes/zelglihof/route'
import { Route as JublawomaIndexRouteImport } from './routes/jublawoma/index'
import { Route as OliumbiIndexRouteImport } from './routes/oliumbi/index'
import { Route as UncletIndexRouteImport } from './routes/unclet/index'
import { Route as ZelglihofIndexRouteImport } from './routes/zelglihof/index'
import { Route as ZelglihofAboutRouteImport } from './routes/zelglihof/about'
import { Route as ZelglihofProductsIndexRouteImport } from './routes/zelglihof/products/index'
import { Route as ZelglihofProductsProductIdRouteImport } from './routes/zelglihof/products/$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZelglihofRouteRoute = ZelglihofRouteRouteImport.update({
  id: '/zelglihof',
  path: '/zelglihof',
  getParentRoute: () => rootRouteImport,
} as any)
const JublawomaIndexRoute = JublawomaIndexRouteImport.update({
  id: '/jublawoma/',
  path: '/jublawoma/',
  getParentRoute: () => rootRouteImport,
} as any)
const OliumbiIndexRoute = OliumbiIndexRouteImport.update({
  id: '/oliumbi/',
  path: '/oliumbi/',
  getParentRoute: () => rootRouteImport,
} as any)
const UncletIndexRoute = UncletIndexRouteImport.update({
  id: '/unclet/',
  path: '/unclet/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZelglihofIndexRoute = ZelglihofIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ZelglihofRouteRoute,
} as any)
const ZelglihofAboutRoute = ZelglihofAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => ZelglihofRouteRoute,
} as any)
const ZelglihofProductsIndexRoute = ZelglihofProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => ZelglihofRouteRoute,
} as any)
const ZelglihofProductsProductIdRoute =
  ZelglihofProductsProductIdRouteImport.update({
    id: '/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => ZelglihofRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/zelglihof': typeof ZelglihofRouteRouteWithChildren
  '/zelglihof/about': typeof ZelglihofAboutRoute
  '/jublawoma/': typeof JublawomaIndexRoute
  '/oliumbi/': typeof OliumbiIndexRoute
  '/unclet/': typeof UncletIndexRoute
  '/zelglihof/': typeof ZelglihofIndexRoute
  '/zelglihof/products/$productId': typeof ZelglihofProductsProductIdRoute
  '/zelglihof/products/': typeof ZelglihofProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/zelglihof/about': typeof ZelglihofAboutRoute
  '/jublawoma': typeof JublawomaIndexRoute
  '/oliumbi': typeof OliumbiIndexRoute
  '/unclet': typeof UncletIndexRoute
  '/zelglihof': typeof ZelglihofIndexRoute
  '/zelglihof/products/$productId': typeof ZelglihofProductsProductIdRoute
  '/zelglihof/products': typeof ZelglihofProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/zelglihof': typeof ZelglihofRouteRouteWithChildren
  '/zelglihof/about': typeof ZelglihofAboutRoute
  '/jublawoma/': typeof JublawomaIndexRoute
  '/oliumbi/': typeof OliumbiIndexRoute
  '/unclet/': typeof UncletIndexRoute
  '/zelglihof/': typeof ZelglihofIndexRoute
  '/zelglihof/products/$productId': typeof ZelglihofProductsProductIdRoute
  '/zelglihof/products/': typeof ZelglihofProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/zelglihof'
    | '/zelglihof/about'
    | '/jublawoma/'
    | '/oliumbi/'
    | '/unclet/'
    | '/zelglihof/'
    | '/zelglihof/products/$productId'
    | '/zelglihof/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/zelglihof/about'
    | '/jublawoma'
    | '/oliumbi'
    | '/unclet'
    | '/zelglihof'
    | '/zelglihof/products/$productId'
    | '/zelglihof/products'
  id:
    | '__root__'
    | '/'
    | '/zelglihof'
    | '/zelglihof/about'
    | '/jublawoma/'
    | '/oliumbi/'
    | '/unclet/'
    | '/zelglihof/'
    | '/zelglihof/products/$productId'
    | '/zelglihof/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ZelglihofRouteRoute: typeof ZelglihofRouteRouteWithChildren
  JublawomaIndexRoute: typeof JublawomaIndexRoute
  OliumbiIndexRoute: typeof OliumbiIndexRoute
  UncletIndexRoute: typeof UncletIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zelglihof': {
      id: '/zelglihof'
      path: '/zelglihof'
      fullPath: '/zelglihof'
      preLoaderRoute: typeof ZelglihofRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jublawoma/': {
      id: '/jublawoma/'
      path: '/jublawoma'
      fullPath: '/jublawoma/'
      preLoaderRoute: typeof JublawomaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oliumbi/': {
      id: '/oliumbi/'
      path: '/oliumbi'
      fullPath: '/oliumbi/'
      preLoaderRoute: typeof OliumbiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unclet/': {
      id: '/unclet/'
      path: '/unclet'
      fullPath: '/unclet/'
      preLoaderRoute: typeof UncletIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zelglihof/': {
      id: '/zelglihof/'
      path: '/'
      fullPath: '/zelglihof/'
      preLoaderRoute: typeof ZelglihofIndexRouteImport
      parentRoute: typeof ZelglihofRouteRoute
    }
    '/zelglihof/about': {
      id: '/zelglihof/about'
      path: '/about'
      fullPath: '/zelglihof/about'
      preLoaderRoute: typeof ZelglihofAboutRouteImport
      parentRoute: typeof ZelglihofRouteRoute
    }
    '/zelglihof/products/': {
      id: '/zelglihof/products/'
      path: '/products'
      fullPath: '/zelglihof/products/'
      preLoaderRoute: typeof ZelglihofProductsIndexRouteImport
      parentRoute: typeof ZelglihofRouteRoute
    }
    '/zelglihof/products/$productId': {
      id: '/zelglihof/products/$productId'
      path: '/products/$productId'
      fullPath: '/zelglihof/products/$productId'
      preLoaderRoute: typeof ZelglihofProductsProductIdRouteImport
      parentRoute: typeof ZelglihofRouteRoute
    }
  }
}

interface ZelglihofRouteRouteChildren {
  ZelglihofAboutRoute: typeof ZelglihofAboutRoute
  ZelglihofIndexRoute: typeof ZelglihofIndexRoute
  ZelglihofProductsProductIdRoute: typeof ZelglihofProductsProductIdRoute
  ZelglihofProductsIndexRoute: typeof ZelglihofProductsIndexRoute
}

const ZelglihofRouteRouteChildren: ZelglihofRouteRouteChildren = {
  ZelglihofAboutRoute: ZelglihofAboutRoute,
  ZelglihofIndexRoute: ZelglihofIndexRoute,
  ZelglihofProductsProductIdRoute: ZelglihofProductsProductIdRoute,
  ZelglihofProductsIndexRoute: ZelglihofProductsIndexRoute,
}

const ZelglihofRouteRouteWithChildren = ZelglihofRouteRoute._addFileChildren(
  ZelglihofRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ZelglihofRouteRoute: ZelglihofRouteRouteWithChildren,
  JublawomaIndexRoute: JublawomaIndexRoute,
  OliumbiIndexRoute: OliumbiIndexRoute,
  UncletIndexRoute: UncletIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
